[workspace]
resolver = "2"
members = [
    "agenda-files",
    "cal-sync", "roam-export",
]
default-members = ["cal-sync", "agenda-files", "roam-export"]

[workspace.package]
authors = ["David Minh-Duy Cao <david@cao.sh>"]
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

