[package]
name = "fix-prop-drawers"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
argh = "0.1"
walkdir = "2"
rayon = "1"
color-eyre = "0.6"

regex = "1"

jiff = "0.1"

orgize = "0.10.0-alpha.10"
slug = "0.1"

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
